# Generated by Django 2.1.3 on 2018-11-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.IntegerField(verbose_name='금액'),
        ),
    ]
