# Generated by Django 2.1.3 on 2018-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='activity',
            field=models.IntegerField(blank=True, null=True, verbose_name='사용 금액'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='budgeted',
            field=models.IntegerField(blank=True, null=True, verbose_name='예산 금액'),
        ),
    ]
