# Generated by Django 2.1.3 on 2018-11-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20181107_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='년'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(verbose_name='월'),
        ),
    ]
