# Generated by Django 2.1.3 on 2018-11-08 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0007_auto_20181108_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='spent',
            field=models.IntegerField(default=0, verbose_name='금액'),
        ),
    ]
