# Generated by Django 2.1.3 on 2018-11-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20181108_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetitem',
            old_name='spent',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='amount',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budgeted',
            field=models.IntegerField(default=0, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=11, verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='년'),
        ),
    ]
