# Generated by Django 2.1.3 on 2018-11-09 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20181108_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year_month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='언제'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='activity',
            field=models.IntegerField(default=0, verbose_name='사용 금액'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='budgeted',
            field=models.IntegerField(default=0, verbose_name='예산 금액'),
        ),
    ]
